[package]
name = "IronPress"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
json = "0.12.4"
num-complex = "0.4.3"
