name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cached LFS checkout
      uses: nschloe/action-cached-lfs-checkout@v1.1.2
      # with:
      #   # Explicitly include files for LFS
      #   include: # optional, default is *
      #   # Explicitly exclude files for LFS
      #   exclude: # optional, default is nothing
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
